# Generated by Django 3.1.5 on 2021-01-06 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosVendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('cimadireita', 'Cima Direita'), ('cimaesquerda', 'Cima Esquerda'), ('baixoesquerda', 'Baixo Esquerda'), ('baixodireita', 'Baixo Direita')], max_length=30)),
                ('status', models.IntegerField()),
                ('produto_vendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.produtosvendidos')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDisponiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.sensores')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.statusdisponiveis')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('validade', models.DateField(auto_now_add=True)),
                ('produto_vendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.produtosvendidos')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_vendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.produtosvendidos')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=400)),
                ('telefone', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.empresa')),
            ],
        ),
    ]
