# Generated by Django 3.1.5 on 2021-01-06 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='modelo',
        ),
        migrations.AddField(
            model_name='eventos',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker.sensores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='chave',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tracker.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='produto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='validado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produtosvendidos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.modelos')),
            ],
        ),
    ]
