# Generated by Django 3.1.5 on 2021-01-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210106_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='envio',
        ),
    ]
