# Generated by Django 3.1.5 on 2021-01-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210106_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.envio'),
        ),
    ]
