# Generated by Django 3.1.5 on 2021-01-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210106_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='envio',
            new_name='envio_relacionado',
        ),
    ]
