# Generated by Django 3.1.5 on 2021-01-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20210106_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosvendidos',
            name='conectado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='tracker.envio'),
        ),
    ]
