# Generated by Django 3.1.5 on 2021-01-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210107_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosvendidos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.produtos'),
        ),
    ]
